DATA_DIR: "C:\\data\\HUKsvoc\\data"

# BENCHMARK_DATA_FILENAME: "HUK_cga_data.csv"
# BENCHMARK_COLUMNS:
#   ID: 'CgaId'
#   OUTLET_NAME: 'OutletName'
#   POSTCODE: 'Postcode'
#   ADDRESS: 'OutletAddress'

# INPUT_DATA_FILENAME: "HUK_bowimi_data.csv"
# INPUT_COLUMNS:
#   ID: 'BowimiId'
#   OUTLET_NAME: 'OutletName'
#   POSTCODE: 'OutletPostCode'
#   ADDRESS: 'OutletAddress'

BENCHMARK_DATA_FILENAME: "CGA.csv"
BENCHMARK_COLUMNS:
  ID: 'cgacode'
  OUTLET_NAME: 'outletname'
  POSTCODE: 'outletpostcode'
  ADDRESS: 'outletaddress'
  LATITUDE: 'latitude'
  LONGITUDE: 'longitude'

INPUT_DATA_FILENAME: "STGT.csv"
INPUT_COLUMNS:
  ID: 'ontoftcode'
  OUTLET_NAME: 'outletname'
  POSTCODE: 'outletpostcode'
  ADDRESS: 'outletaddress'
  LATITUDE: 'latitude'
  LONGITUDE: 'longitude'